apiVersion: apps/v1
kind: Deployment
metadata:
  name: personicle-auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personicle-auth-service
  template:
    metadata:
      labels:
        app: personicle-auth-service
    spec:
      containers:
      - name: personicle-auth-service
        image: personicleservices.azurecr.io/personicle-authentication-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: CLIENT_USERINFO_URI
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CLIENT_USERINFO_URI
        - name: USER_INFO_URI
          valueFrom:
            secretKeyRef:
              name: secrets
              key: USER_INFO_URI
        - name: CLIENT_ISSUER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CLIENT_ISSUER
        - name: ISSUER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: ISSUER
        - name: CREDENTIALS_DB_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CREDENTIALS_DB_USER
        - name: CREDENTIALS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CREDENTIALS_DB_PASSWORD
        - name: CREDENTIALS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CREDENTIALS_DB_HOST
        - name: CREDENTIALS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CREDENTIALS_DB_NAME
        - name: GET_USER_GROUP_TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: GET_USER_GROUP_TOKEN
        - name: USER_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: USER_ENDPOINT
        - name: PHYSICIAN_GROUP
          valueFrom:
            secretKeyRef:
              name: secrets
              key: PHYSICIAN_GROUP
        
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: personicle-auth-service
spec:
  ports:
  - port: 5000
    name: auth-service
    protocol: TCP
    targetPort: 5000
  selector:
    app: personicle-auth-service
